import { site } from "./content.js";

const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[character]));
const route = (path) => `<a href="${path}" data-route`;

export const bookCover = (book, className = "") => `<div class="book-cover ${className}"><img src="${escapeHtml(book.coverUrl)}" alt="${escapeHtml(book.coverAlt)}" loading="lazy" /></div>`;
export const bookCard = (book) => `<article class="book-card" data-book-id="${escapeHtml(book.id)}" data-book-slug="${escapeHtml(book.slug)}">${route(`/books/${encodeURIComponent(book.slug)}`)} class="book-link" aria-label="View ${escapeHtml(book.title)}">${bookCover(book)}<h3 class="book-title">${escapeHtml(book.title)}</h3><p class="book-description">${escapeHtml(book.genre)}</p></a></article>`;
export const newsletterBlock = (id = "main") => `<section class="newsletter-panel" aria-labelledby="newsletter-heading"><p class="eyebrow">Stay in touch</p><h2 id="newsletter-heading">A letter, now and then.</h2><p>Book news and occasional notes from Deborah—approximately every three to four weeks. You can unsubscribe at any time.</p><form class="newsletter-form" data-endpoint="${site.api.newsletterSubscribe}" novalidate><label for="${id}-email">Email address</label><div><input id="${id}-email" name="email" type="email" autocomplete="email" placeholder="Your email address" required /><button type="submit">Join the list</button></div><p class="form-message" aria-live="polite"></p></form></section>`;

export function homeView(books) {
  const featured = books.find((book) => book.featured) || books[0];
  return `<div class="page"><section class="hero"><div><p class="eyebrow">Mystery novels</p><h1>Mystery novels by <em>Deborah Fowler.</em></h1><p class="hero-copy placeholder">placeholder area for text</p><div class="hero-actions">${route("/books")} class="button">View the books</a>${route("/about")} class="button button-outline">About Deborah</a></div></div><figure class="author-photo hero-photo"><img src="${site.author.photoUrl}" alt="${site.author.photoAlt}" /><figcaption>Deborah Fowler <span>Author portrait</span></figcaption></figure></section><section class="section"><div class="section-heading"><div><p class="eyebrow">Featured title</p><h2>${escapeHtml(featured.title)}</h2></div>${route("/books")} class="text-link">All books</a></div><div class="feature-book">${bookCover(featured)}<div><p class="placeholder">${featured.isPlaceholder ? "Book description to come" : "Featured book"}</p><h2>${escapeHtml(featured.title)}</h2><p>${escapeHtml(featured.description)}</p>${route(`/books/${featured.slug}`)} class="button">About this book</a></div></div></section><section class="section section-tint"><div class="section-heading"><div><p class="eyebrow">The books</p><h2>Browse Deborah’s books</h2></div>${route("/books")} class="text-link">See all books</a></div><div class="book-grid">${books.slice(0, 5).map(bookCard).join("")}</div></section>${newsletterBlock("home")}</div>`;
}
export function aboutView() { return `<div class="page"><section class="page-intro"><p class="eyebrow">About the author</p><h1>${site.author.name}</h1><p class="placeholder">placeholder area for text</p></section><section class="section section-tint"><div class="about-grid"><figure class="author-photo about-photo"><img src="${site.author.photoUrl}" alt="${site.author.photoAlt}" /></figure><div class="prose"><p class="placeholder">Biography placeholder — replace before launch</p><h2>A few words from Deborah</h2>${site.author.biography.map((paragraph) => `<p>${escapeHtml(paragraph)}</p>`).join("")}${route("/newsletter")} class="button">Receive occasional news</a></div></div></section></div>`; }
export function booksView(books) { return `<div class="page"><section class="page-intro"><p class="eyebrow">Books</p><h1>The Deborah Fowler bookshelf</h1><p class="placeholder">placeholder area for text</p></section><section class="section section-tint"><div class="book-grid">${books.map(bookCard).join("")}</div></section></div>`; }
export function bookDetailView(book) { if (!book) return notFoundView(); const details = [book.publicationDate && `Published ${book.publicationDate}`, book.genre, book.isbn && `ISBN ${book.isbn}`].filter(Boolean).join(" · "); const purchase = book.purchaseLinks.length ? `<div class="purchase-links">${book.purchaseLinks.map((link) => `<a class="button" href="${escapeHtml(link.url)}" target="_blank" rel="noopener noreferrer">${escapeHtml(link.label)}</a>`).join("")}</div>` : `<p class="buy-placeholder">Purchase links will be added when they are available.</p>`; return `<div class="page"><section class="section"><a class="text-link" href="/books" data-route>← All books</a><div class="book-detail"><div>${bookCover(book)}<p class="book-meta">${escapeHtml(details)}</p></div><div><p class="eyebrow">${escapeHtml(book.genre)}</p><h1>${escapeHtml(book.title)}</h1><p class="placeholder">${book.isPlaceholder ? "Placeholder description" : "About the book"}</p><p>${escapeHtml(book.description)}</p>${book.extract ? `<blockquote class="extract">“${escapeHtml(book.extract)}”</blockquote><p class="placeholder">Brief sample</p>` : ""}${purchase}</div></div></section></div>`; }
export function newsletterView() { const confirmed = new URLSearchParams(window.location.search).get("confirmed") === "1"; return `<div class="page"><section class="page-intro"><p class="eyebrow">Newsletter</p><h1>A note for readers.</h1>${confirmed ? '<p class="form-confirmation" role="status">Thank you—your email address has been confirmed.</p>' : ""}<p class="placeholder">placeholder area for text</p></section>${newsletterBlock("newsletter")}</div>`; }
export function contactView() { return `<div class="page"><section class="section"><div class="contact-layout"><div><p class="eyebrow">Contact</p><h1>Get in touch</h1><p class="placeholder">placeholder area for text</p></div><form class="contact-form" data-endpoint="${site.api.contact}" novalidate><label>Name<input name="name" required autocomplete="name" /></label><label>Email<input name="email" type="email" required autocomplete="email" /></label><label>Message<textarea name="message" required></textarea></label><button class="button" type="submit">Send message</button><p class="form-message" aria-live="polite"></p><p class="privacy-note">The form will send to Deborah’s chosen contact address when the website backend is connected.</p></form></div></section></div>`; }
export function notFoundView() { return `<section class="section page"><div class="prose"><p class="eyebrow">Not found</p><h1>That page isn’t here.</h1>${route("/")} class="button">Return home</a></div></section>`; }
